### ISSUE TITLE
Node version restricted to 9.4.0

### ISSUE THREAD

**Issue by Hyjaz** [Electra-project/electra-js#1]
Is there any reason that this library is restricted to node version 9.4.0?

**Comment by ivangabriele** [comment]
It's an extra measure of safety, and easy one since this the version I'm working with. However I can extend the tests to see if it works well with lower major versions. The issue is that we have some security flaws related to certain minor version concerning multiple major ones. I'm not sure we can specify multiple node engine version there but I didn't check that yet.

**Comment by ivangabriele** [comment]
Fixed in v0.14.5.
