### ISSUE TITLE
Error: webServices#getBalanceFor(): XMLHttpRequest is not defined in Node.js

### ISSUE THREAD

**Issue by topguru** [Electra-project/electra-js#2]
I am getting the following error when run getBalance() function in node.js

My code snippet is as following:
var ElectraJs = require('electra-js');
const electraJs = new ElectraJs();
electraJs.wallet.getBalance(address);

I need your help ASAP.
Thank you!

**Comment by ivangabriele** [comment]
@topguru ElectraJs is indeed still an work in progress but I will check that asap.

**Comment by topguru** [comment]
@ivangabriele , Thank you!
Node 8.10.0
Mac
What information do you need more?
As I am working on urgent project, I want you to review this issue ASAP.

**Comment by ivangabriele** [comment]
But the thing @topguru is that you won't be able to use the wallet in production if that's your goal. It's really a work in progress right now and many methods don't work: you can't send a transaction, you can't list the transactions history, the import/export have not been tested...

**Comment by Hyjaz** [comment]
@topguru You should use node v9.4.0. I am not certain how you were able to install electra-js on node v8.10.0.

Try it with node v9.4.0, and get back to us.

**Comment by topguru** [comment]
If supports with only v9.4.0, it is unable to use. Because the recommended latest node.js version is v8.10.

**Comment by ivangabriele** [comment]
Yes @topguru I didn't have time to test it on other versions yet. Again as I told before it's a work in progress, it's not even a beta version yet.

**Comment by ivangabriele** [comment]
@topguru  When you call `new ElectraJs()` without any parameter, you are actually calling the light wallet version, which [requires a Browser-like environment](https://github.com/Electra-project/electra-js#light-wallet-vs-hard-wallet). That's why you get the `XMLHttpRequest is not defined in Node.js` error.

You need to specify `const electraJs = new ElectraJs({ hard: true })` to switch to the hard wallet mode which is adapted to a NodeJS environment.

You also don't start the wallet correctly, I invite you to check the [hard wallet example](https://github.com/Electra-project/electra-js-example-hard) I created to see how it works.

I also just updated the engines to include NodeJS v8 & npm v5 since my tests passed on it. It's thus fixed in the version 0.14.5.

**Comment by ivangabriele** [comment]
I'm closing that.
